// Generated by CoffeeScript 1.10.0
(function() {
  if (document.title === CONFIG_UUID) {
    new ButtonFrameContent(Hash.decode());
  } else {
    new Deferred(function() {
      var anchor, anchors, fn, i, len;
      if (document.querySelectorAll) {
        anchors = document.querySelectorAll("a." + CONFIG_ANCHOR_CLASS);
      } else {
        anchors = (function() {
          var i, len, ref, results;
          ref = document.getElementsByTagName("a");
          results = [];
          for (i = 0, len = ref.length; i < len; i++) {
            anchor = ref[i];
            if (new Element(anchor).hasClass(CONFIG_ANCHOR_CLASS)) {
              results.push(anchor);
            }
          }
          return results;
        })();
      }
      fn = function(a) {
        new ButtonFrame(Hash.encode(ButtonAnchor.parse(a)), function(iframe) {
          document.body.appendChild(iframe);
        }, function(iframe) {
          a.parentNode.replaceChild(iframe, a);
        });
      };
      for (i = 0, len = anchors.length; i < len; i++) {
        anchor = anchors[i];
        fn(anchor);
      }
    });
  }

}).call(this);
