CONFIG_API          = "https://api.github.com"
CONFIG_ANCHOR_CLASS = "dimensiondata-button"
CONFIG_ICON_CLASS   = "octicon"
CONFIG_ICON_DEFAULT = "#{CONFIG_ICON_CLASS}-cloud-upload"
CONFIG_URL          = if document.currentScript then document.currentScript.src.replace /[^/]*([?#].*)?$/, "" else "#{if /^http:/.test document.location then "http" else "https"}://dimensiondataresearch.github.io/buttons/"
CONFIG_UUID         = "faa75404-3b97-5585-b449-4bc51338fbd1"
