// Generated by CoffeeScript 1.10.0
(function() {
  var CONFIG_ANCHOR_CLASS, CONFIG_API, CONFIG_ICON_CLASS, CONFIG_ICON_DEFAULT, CONFIG_URL, CONFIG_UUID;

  CONFIG_API = "https://api.github.com";

  CONFIG_ANCHOR_CLASS = "dimensiondata-button";

  CONFIG_ICON_CLASS = "octicon";

  CONFIG_ICON_DEFAULT = CONFIG_ICON_CLASS + "-cloud-upload";

  CONFIG_URL = document.currentScript ? document.currentScript.src.replace(/[^\/]*([?#].*)?$/, "") : (/^http:/.test(document.location) ? "http" : "https") + "://dimensiondataresearch.github.io/buttons/";

  CONFIG_UUID = "faa75404-3b97-5585-b449-4bc51338fbd1";

}).call(this);
