// Generated by CoffeeScript 1.10.0
(function() {
  var Deferred;

  Deferred = (function() {
    function Deferred(func) {
      var callback;
      if (/m/.test(document.readyState) || (!/g/.test(document.readyState) && !document.documentElement.doScroll)) {
        window.setTimeout(func);
      } else {
        if (document.addEventListener) {
          new EventTarget(document).once("DOMContentLoaded", func);
        } else {
          callback = function() {
            if (/m/.test(document.readyState)) {
              document.detachEvent("onreadystatechange", callback);
              if (func) {
                func();
              }
            }
          };
          document.attachEvent("onreadystatechange", callback);
        }
      }
    }

    return Deferred;

  })();

}).call(this);
